moto c_isalnum.moto > c_isalnum.txt 	
moto c_isalpha.moto > c_isalpha.txt
moto c_iscntrl.moto > c_iscntrl.txt 
moto c_isdigit.moto > c_isdigit.txt
moto c_isgraph.moto > c_isgraph.txt
moto c_islower.moto > c_islower.txt
moto c_isprint.moto > c_isprint.txt
moto c_ispunct.moto > c_ispunct.txt
moto c_isspace.moto > c_isspace.txt
moto c_isupper.moto > c_isupper.txt
moto c_isxdigit.moto > c_isxdigit.txt
moto c_tolower.moto > c_tolower.txt
moto c_toupper.moto > c_toupper.txt
